# Generated by Django 4.0.2 on 2024-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('fee_int', models.IntegerField()),
                ('fee_int_currency', models.CharField(max_length=20)),
                ('fee_nat', models.IntegerField()),
                ('fee_nat_currency', models.CharField(max_length=20)),
                ('duration', models.SmallIntegerField(null=True)),
                ('university', models.CharField(max_length=200)),
                ('university_logo', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('fullonline', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=True)),
                ('oncampus', models.BooleanField(default=True)),
                ('fulltime', models.BooleanField(default=True)),
                ('parttime', models.BooleanField(default=True)),
                ('ielts', models.SmallIntegerField(null=True)),
                ('toefl', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
