# Generated by Django 4.2.11 on 2024-04-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BPCollege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("fee_int", models.IntegerField(null=True)),
                ("fee_int_currency", models.CharField(max_length=20)),
                ("fee_nat", models.IntegerField(null=True)),
                ("fee_nat_currency", models.CharField(max_length=20)),
                ("duration", models.SmallIntegerField(null=True)),
                ("university", models.CharField(max_length=200)),
                ("university_logo", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("fullonline", models.BooleanField(null=True)),
                ("online", models.BooleanField(null=True)),
                ("oncampus", models.BooleanField(null=True)),
                ("fulltime", models.BooleanField(null=True)),
                ("parttime", models.BooleanField(null=True)),
                ("ielts", models.SmallIntegerField(null=True)),
                ("toefl", models.SmallIntegerField(null=True)),
            ],
        ),
    ]
