# Generated by Django 4.2.11 on 2025-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelorsportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpcollege',
            name='code',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
