# Generated by Django 4.2.11 on 2025-06-27 09:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('place', models.CharField(max_length=180)),
                ('admin_name1', models.CharField(max_length=100)),
                ('admin_code1', models.CharField(max_length=20)),
                ('admin_name2', models.CharField(max_length=100)),
                ('admin_code2', models.CharField(max_length=20)),
                ('admin_name3', models.CharField(max_length=100)),
                ('admin_code3', models.CharField(max_length=20)),
                ('lat', models.CharField(blank=True, max_length=30)),
                ('lon', models.CharField(blank=True, max_length=30)),
                ('accuracy', models.SmallIntegerField()),
                ('GEOMETRY', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
