# Generated by Django 4.2.11 on 2025-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('edit_type', models.CharField(choices=[('add', 'add'), ('edit', 'edit'), ('del', 'delete')], default='add', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='accuracy',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='admin_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='admin_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='admin_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
