# Generated by Django 4.2.11 on 2024-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="lat",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="school",
            name="lon",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
