# Generated by Django 4.2.11 on 2024-07-22 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_lat_school_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='keralaschool',
            name='GEOMETRY',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='keralaschool',
            name='udise_code',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
