# Generated by Django 4.2.11 on 2024-07-20 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_lat_school_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='keralaschool',
            name='GEOMETRY',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
