# Generated by Django 4.2.11 on 2025-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_staffdetails_staffdesig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keralaschool',
            name='code',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='keralaschool',
            name='udise_code',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='school',
            name='block',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='school',
            name='udise_code',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
